version: "3.9"

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab1

volumes:
  db_data: { }

