spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/lab1
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    flyway.enabled: true

flyway:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lab1
  user: ${DB_USER}
  password: ${DB_PASS}